apiVersion: app.kiegroup.org/v1beta1
kind: KogitoRuntime
metadata:
  name: order-kogito-runtime
spec:
  replicas: 1
  image: order-kogito-runtime
  insecureImageRegistry: true
  probes:
    livenessProbe:
      httpGet:
        path: /probes/live # Liveness endpoint
        port: 8080
    readinessProbe:
      httpGet:
        path: /probes/ready # Readiness endpoint
        port: 8080
    startupProbe:
      tcpSocket:
        port: 8080
  # Reference to the KogitoInfra resource with the Knative Broker binding
  infra:
  - kogito-kafka-infra
  env:
  - name: QUARKUS_DATASOURCE_USERNAME
    value: kogito-user
  - name: QUARKUS_DATASOURCE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: postgresql
        key: database-password
  - name: QUARKUS_DATASOURCE_REACTIVE_URL
    value: postgresql://postgresql:5432/kogito
  - name: QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION
    value: update
